/**
 * Interpretive lookup tables for the Semar web app.
 * Purely static data — no imports needed.
 */

// ── I-Ching ───────────────────────────────────────────────────────────────────

export const HEXAGRAM_GUIDANCE: Record<number, string> = {
  1:  'Supreme creative force — act with perseverance and heavenly virtue',
  2:  'Yield and receive — strength flows through devoted, receptive service',
  3:  'Push through initial chaos — seek allies, do not act alone',
  4:  'Embrace the beginner\'s mind — sincerity opens the teacher\'s door',
  5:  'Wait with inner strength and confidence — the right moment will come',
  6:  'Seek mediation, not victory — withdraw before the conflict deepens',
  7:  'Discipline and order win — choose a trusted leader and follow through',
  8:  'Unite now without hesitation — those who wait will be left behind',
  9:  'Clouds gather but no rain yet — refine your plans before acting',
  10: 'Walk carefully near danger — sincerity and courtesy protect you',
  11: 'Heaven and earth unite in peace — great success, maintain humility',
  12: 'Heaven and earth are blocked — retreat, preserve strength, do not force',
  13: 'Open fellowship with broad vision — unite beyond your inner circle',
  14: 'Great abundance is yours — use it to serve the greater good',
  15: 'Modesty succeeds in all directions — the humble person meets no resistance',
  16: 'Align with genuine enthusiasm — inspire others and set things in motion',
  17: 'Follow the current of the moment — surrender to what is natural now',
  18: 'Face what has been neglected — decisive work restores lost vitality',
  19: 'Good fortune approaches steadily — receive it through clear intention',
  20: 'Step back and observe deeply — insight must precede any action',
  21: 'Bite through the obstacle — decisive action clears what blocks the path',
  22: 'Grace and beauty adorn truth — use form to illuminate, not replace, substance',
  23: 'Endure the stripping away — the seed within remains intact and will return',
  24: 'The light begins to return — rest in stillness as the new cycle opens',
  25: 'Act from pure heart without calculation — trust the natural unfolding',
  26: 'Accumulate through restraint — the stored energy nears its moment of release',
  27: 'Choose your nourishment wisely — what you feed body and mind becomes you',
  28: 'The ridgepole is bending — exceptional circumstances require bold action now',
  29: 'Move through the abyss with a sincere heart — sincerity finds the way through',
  30: 'Cling to what gives light — clarity and persistence illuminate the path forward',
  31: 'Open, receptive influence — the heart moves naturally when it remains empty',
  32: 'Persevere in what is right — duration requires you not to shift direction',
  33: 'Graceful withdrawal preserves strength — retreat now to advance more fully later',
  34: 'Channel great power through right conduct — force without virtue destroys itself',
  35: 'Advance toward the light — recognition comes to those who proceed with virtue',
  36: 'Conceal your brightness — persevere inwardly through this time of eclipse',
  37: 'Order begins at home — clarity of roles and duties creates lasting harmony',
  38: 'In small matters good fortune — meet difference with understanding, not opposition',
  39: 'Turn inward at the obstruction — the obstacle itself is the path to mastery',
  40: 'Tension releases — act swiftly to seize the opening while it remains',
  41: 'Decrease below to increase above — sincere offering brings unexpected good fortune',
  42: 'The time of increase is here — act decisively while fortune flows strongly',
  43: 'Declare the truth resolutely — use clarity and example, not force or anger',
  44: 'Remain vigilant — what seems small and harmless can grow to overwhelm',
  45: 'Gather with clear purpose and sincere rites — unity multiplies strength',
  46: 'Steadily push upward without haste — the time strongly favors gradual ascent',
  47: 'Speak little in adversity — the steadfast mind triumphs where force cannot',
  48: 'Serve the essential need consistently — the inexhaustible source rewards maintenance',
  49: 'The time demands transformation — change when the season is fully ripe',
  50: 'The sacred vessel transforms what enters — nourish greatness through refinement',
  51: 'Shock awakens — remain calm and inward, and the fear turns to blessing',
  52: 'Know when to stop — stillness at the right moment restores the proper order',
  53: 'Develop gradually and organically — patient growth like a tree endures all winds',
  54: 'Proceed with clear eyes — subordinate position now can build a lasting bond',
  55: 'At the peak of abundance — shine fully and clearly while the sun is high',
  56: 'Move lightly without attachment — the wanderer survives through care and courtesy',
  57: 'Penetrate gently and persistently — small repeated actions compound into great effect',
  58: 'Genuine joy comes from inner strength — open joyfulness without flattery or excess',
  59: 'Dissolve rigidity and separation — reunite the scattered through shared higher purpose',
  60: 'Joyful limitation is wisdom — embrace what is truly sustainable and necessary',
  61: 'Inner truth penetrates all barriers — sincere presence transforms without force',
  62: 'Small excess brings success now — do not attempt the great, attend to the small',
  63: 'After completion, stay vigilant — success contains the seeds of the next change',
  64: 'Not yet complete — cross the water with great care, the end is within sight',
};

// ── Tarot ─────────────────────────────────────────────────────────────────────

export const TAROT_MEANINGS: Record<string, { upright: string; reversed: string }> = {
  // Major Arcana
  'The Fool':           { upright: 'new beginnings, freedom, leap of faith',        reversed: 'recklessness, poor judgment, naivety' },
  'The Magician':       { upright: 'willpower, skill, manifestation',               reversed: 'manipulation, wasted talent, deception' },
  'The High Priestess': { upright: 'intuition, mystery, inner knowing',             reversed: 'secrets withheld, disconnection from self' },
  'The Empress':        { upright: 'abundance, fertility, nurturing love',           reversed: 'dependence, creative block, neglect' },
  'The Emperor':        { upright: 'authority, structure, fatherly stability',       reversed: 'rigidity, domination, inflexibility' },
  'The Hierophant':     { upright: 'tradition, spiritual guidance, institutions',    reversed: 'rebellion, unorthodox path, questioning norms' },
  'The Lovers':         { upright: 'love, harmony, aligned values',                 reversed: 'disharmony, imbalance, misalignment' },
  'The Chariot':        { upright: 'victory, determination, willpower',             reversed: 'lack of direction, scattered energy' },
  'Strength':           { upright: 'inner courage, patience, compassion',           reversed: 'self-doubt, weakness, insecurity' },
  'The Hermit':         { upright: 'soul-searching, inner guidance, solitude',      reversed: 'isolation, loneliness, withdrawal' },
  'Wheel of Fortune':   { upright: 'luck, cycles, turning point',                   reversed: 'bad luck, resistance to change, stagnation' },
  'Justice':            { upright: 'truth, fairness, accountability',               reversed: 'injustice, dishonesty, bias' },
  'The Hanged Man':     { upright: 'pause, surrender, new perspective',             reversed: 'delays, resistance, stagnation' },
  'Death':              { upright: 'endings, transformation, transition',           reversed: 'resistance to change, inability to move on' },
  'Temperance':         { upright: 'balance, patience, moderation',                 reversed: 'excess, imbalance, lack of restraint' },
  'The Devil':          { upright: 'bondage, materialism, shadow self',             reversed: 'releasing chains, reclaiming power' },
  'The Tower':          { upright: 'sudden upheaval, revelation, chaos',            reversed: 'avoiding disaster, narrowly escaping ruin' },
  'The Star':           { upright: 'hope, renewal, divine inspiration',             reversed: 'despair, discouragement, lack of faith' },
  'The Moon':           { upright: 'illusion, fear, the subconscious',              reversed: 'confusion lifting, truth emerging' },
  'The Sun':            { upright: 'success, vitality, joy, clarity',              reversed: 'temporary setback, blocked energy' },
  'Judgement':          { upright: 'awakening, reckoning, higher calling',          reversed: 'self-doubt, refusal to heed the call' },
  'The World':          { upright: 'completion, integration, wholeness',            reversed: 'incompleteness, seeking closure' },

  // Wands
  'Ace of Wands':    { upright: 'inspiration, new passion, creative spark',       reversed: 'delays, blocked creativity, false start' },
  '2 of Wands':      { upright: 'planning, vision, stepping into the world',      reversed: 'fear of unknown, poor planning, stagnation' },
  '3 of Wands':      { upright: 'expansion, foresight, enterprise',               reversed: 'delays, obstacles to progress, lack of vision' },
  '4 of Wands':      { upright: 'celebration, homecoming, stable foundation',     reversed: 'instability, lack of harmony at home' },
  '5 of Wands':      { upright: 'conflict, competition, disagreement',            reversed: 'avoiding conflict, finding common ground' },
  '6 of Wands':      { upright: 'victory, public recognition, achievement',       reversed: 'ego, fall from grace, self-doubt' },
  '7 of Wands':      { upright: 'perseverance, defensiveness, standing ground',   reversed: 'giving up, overwhelmed by opposition' },
  '8 of Wands':      { upright: 'swift action, movement, momentum',               reversed: 'delays, frustration, miscommunication' },
  '9 of Wands':      { upright: 'resilience, persistence, last stand',            reversed: 'exhaustion, defensiveness, burnout' },
  '10 of Wands':     { upright: 'burden, extra responsibility, hard work',        reversed: 'doing it alone, unable to delegate' },
  'Page of Wands':   { upright: 'exploration, enthusiasm, free spirit',           reversed: 'impulsiveness, lack of direction' },
  'Knight of Wands': { upright: 'energy, passion, fearless adventure',            reversed: 'recklessness, impulsiveness, haste' },
  'Queen of Wands':  { upright: 'confidence, independence, determination',        reversed: 'controlling, demanding, volatile' },
  'King of Wands':   { upright: 'vision, leadership, entrepreneurial spirit',     reversed: 'impulsive authority, overbearing' },

  // Cups
  'Ace of Cups':    { upright: 'new love, emotional opening, intuition',          reversed: 'blocked emotions, emptiness, repression' },
  '2 of Cups':      { upright: 'partnership, mutual attraction, unity',           reversed: 'tension, broken connection, withdrawal' },
  '3 of Cups':      { upright: 'celebration, friendship, community joy',          reversed: 'overindulgence, gossip, isolation' },
  '4 of Cups':      { upright: 'contemplation, apathy, missed opportunity',       reversed: 'motivation returns, new perspective' },
  '5 of Cups':      { upright: 'loss, grief, focusing on what\'s gone',           reversed: 'acceptance, moving forward, hope returns' },
  '6 of Cups':      { upright: 'nostalgia, childhood, past gifts',                reversed: 'living in the past, naivety' },
  '7 of Cups':      { upright: 'fantasy, wishful thinking, many choices',         reversed: 'clarity after illusion, temptation' },
  '8 of Cups':      { upright: 'walking away, seeking deeper meaning',            reversed: 'fear of moving on, staying in misery' },
  '9 of Cups':      { upright: 'wishes granted, satisfaction, contentment',       reversed: 'dissatisfaction, greed, inner emptiness' },
  '10 of Cups':     { upright: 'divine love, harmony, family bliss',              reversed: 'broken home, misaligned values' },
  'Page of Cups':   { upright: 'creative sensitivity, intuitive messages',        reversed: 'emotional immaturity, creative block' },
  'Knight of Cups': { upright: 'romance, charm, following the heart',             reversed: 'moodiness, unrealistic expectations' },
  'Queen of Cups':  { upright: 'compassion, emotional intelligence, intuition',   reversed: 'emotional insecurity, codependency' },
  'King of Cups':   { upright: 'emotional mastery, diplomacy, calm wisdom',       reversed: 'manipulation, emotional volatility' },

  // Swords
  'Ace of Swords':    { upright: 'clarity, truth, new idea cutting through',      reversed: 'confusion, chaos, brutal truth' },
  '2 of Swords':      { upright: 'difficult decision, truce, stalemate',          reversed: 'information overload, indecision' },
  '3 of Swords':      { upright: 'heartbreak, sorrow, painful truth',             reversed: 'recovery, forgiveness, releasing grief' },
  '4 of Swords':      { upright: 'rest, recovery, contemplation',                 reversed: 'restlessness, unable to relax, burnout' },
  '5 of Swords':      { upright: 'conflict, dishonor, hollow victory',            reversed: 'reconciliation, past wounds healing' },
  '6 of Swords':      { upright: 'transition, moving on, calmer waters',          reversed: 'emotionally stuck, unable to move on' },
  '7 of Swords':      { upright: 'deception, strategy, acting alone',             reversed: 'truth revealed, coming clean' },
  '8 of Swords':      { upright: 'restriction, self-imprisonment, victim',        reversed: 'freedom, releasing self-imposed limits' },
  '9 of Swords':      { upright: 'anxiety, nightmares, fear and worry',           reversed: 'releasing worry, shame dissolving' },
  '10 of Swords':     { upright: 'painful ending, betrayal, rock bottom',         reversed: 'rising from ruin, regeneration' },
  'Page of Swords':   { upright: 'curious, witty, alert communicator',            reversed: 'haste, deception, scattershot thinking' },
  'Knight of Swords': { upright: 'direct, driven, decisive action',               reversed: 'aggressive, reckless, scattered' },
  'Queen of Swords':  { upright: 'independent, clear-minded, direct',             reversed: 'coldness, cruelty, bitterness' },
  'King of Swords':   { upright: 'truth, ethics, clear authority',                reversed: 'manipulation, abuse of power' },

  // Pentacles
  'Ace of Pentacles':    { upright: 'new financial opportunity, abundance',       reversed: 'lost opportunity, financial setback' },
  '2 of Pentacles':      { upright: 'balance, adaptability, juggling priorities', reversed: 'overwhelmed, disorganized, imbalance' },
  '3 of Pentacles':      { upright: 'teamwork, skill, collaborative building',    reversed: 'lack of cohesion, poor planning' },
  '4 of Pentacles':      { upright: 'stability, security, conserving resources',  reversed: 'materialism, possessiveness, stinginess' },
  '5 of Pentacles':      { upright: 'financial hardship, poverty, isolation',     reversed: 'recovery, improved circumstances' },
  '6 of Pentacles':      { upright: 'generosity, giving, fair exchange',          reversed: 'debt, strings attached, inequality' },
  '7 of Pentacles':      { upright: 'patience, long-term view, perseverance',     reversed: 'impatience, lack of reward, wasted effort' },
  '8 of Pentacles':      { upright: 'diligence, mastery, focused skill-building', reversed: 'perfectionism, lack of focus' },
  '9 of Pentacles':      { upright: 'abundance, luxury, self-sufficiency',        reversed: 'over-investment, false independence' },
  '10 of Pentacles':     { upright: 'legacy, family wealth, long-term success',   reversed: 'financial failure, unstable foundation' },
  'Page of Pentacles':   { upright: 'ambitious learner, practical dreamer',       reversed: 'procrastination, lack of progress' },
  'Knight of Pentacles': { upright: 'hard work, reliability, methodical',         reversed: 'boredom, perfectionism, stubbornness' },
  'Queen of Pentacles':  { upright: 'nurturing, practical abundance, resourceful',reversed: 'neglecting self, financial anxiety' },
  'King of Pentacles':   { upright: 'wealth, business mastery, reliable security',reversed: 'financially reckless, materialistic' },
};

// ── BaZi ─────────────────────────────────────────────────────────────────────

export const BAZI_STEM: Record<string, string> = {
  甲: 'Wood Yang — inisiatif, pertumbuhan langsung, permulaan baru',
  乙: 'Wood Yin — fleksibilitas, adaptasi kreatif, ketekunan lembut',
  丙: 'Fire Yang — kecerahan, ekspansi, visibilitas tinggi',
  丁: 'Fire Yin — pemurnian, fokus dalam, presisi',
  戊: 'Earth Yang — stabilitas, fondasi kuat, pengasuhan sabar',
  己: 'Earth Yin — konsolidasi, kedalaman tersembunyi, kekuatan halus',
  庚: 'Metal Yang — transformasi, ketegasan, memotong yang tidak perlu',
  辛: 'Metal Yin — pemurnian, keindahan, pelepasan yang anggun',
  壬: 'Water Yang — strategi, aliran, kecerdasan jangkauan jauh',
  癸: 'Water Yin — intuisi, penyelesaian, pembaruan tenang',
};

export const BAZI_BRANCH: Record<string, string> = {
  子: 'Tikus — potensi tersembunyi, diam sebelum bergerak',
  丑: 'Kerbau — akumulasi lambat, kesabaran, ketahanan teguh',
  寅: 'Harimau — momentum maju, keberanian, inisiatif ambisius',
  卯: 'Kelinci — ekspansi, harmoni, koneksi sosial',
  辰: 'Naga — transisi kuat, ambiguitas, transformasi besar',
  巳: 'Ular — kebijaksanaan cermat, tindakan terencana, observasi tajam',
  午: 'Kuda — energi puncak, visibilitas tinggi, aktivitas dinamis',
  未: 'Kambing — refleksi, ekspresi artistik, ketekunan lembut',
  申: 'Monyet — adaptasi cepat, kecerdikan, tikungan tak terduga',
  酉: 'Ayam — presisi, diskernmen kritis, pemurnian detail',
  戌: 'Anjing — kesetiaan, kewaspadaan, menuju penyelesaian',
  亥: 'Babi — penyelesaian, istirahat sebelum pembaruan, akar dalam',
};

// ── Weton ─────────────────────────────────────────────────────────────────────

export const NEPTU_BRIEF: Record<number, string> = {
  7:  'Minimal — hari untuk menahan diri dan mempersiapkan',
  8:  'Sedang — hindari keputusan besar, fokus pada rutinitas',
  9:  'Netral — baik untuk pekerjaan teknis dan administratif',
  10: 'Cukup — ada peluang jika ada usaha ekstra',
  11: 'Aktif — produktif untuk memulai proyek baru',
  12: 'Stabil — energi seimbang, cocok untuk kerja sama',
  13: 'Kuat — hari berenergi tinggi, ideal untuk aksi dan keputusan',
  14: 'Sangat Baik — keberuntungan hadir, niat tulus membuka jalan',
  15: 'Istimewa — hari penuh berkah, manfaatkan sepenuhnya',
  16: 'Puncak — energi luar biasa, jaga agar tidak melampaui batas',
  17: 'Langka — momen terkuat, bawa niat dan kebijaksanaan terbaik',
};

export const WUKU_BRIEF: Record<string, string> = {
  Sinta:         'Kasih sayang dan rumah tangga — awal yang penuh kehangatan',
  Landep:        'Ketajaman pikiran — hari untuk analisis dan keputusan logis',
  Ukir:          'Kreativitas dan ekspresi — baik untuk seni dan inovasi',
  Kulantir:      'Ketekunan menghasilkan — kerja keras mendapat imbalan nyata',
  Tolu:          'Tiga kekuatan bersatu — hari keseimbangan yang stabil',
  Gumbreg:       'Kesuburan dan pertumbuhan — rezeki mengalir dengan lancar',
  Wariga:        'Kehati-hatian diperlukan — kalkulasi sebelum bertindak',
  Warigadean:    'Kebijaksanaan dalam tindakan — pertimbangan matang adalah kunci',
  Julungwangi:   'Kemakmuran dan kebahagiaan — hari-hari indah menanti',
  Sungsang:      'Perlu introspeksi mendalam — sesuatu mungkin terbalik dari perkiraan',
  Dungulan:      'Kemenangan setelah perjuangan — momentum ada di pihakmu',
  Kuningan:      'Pemurnian dan penyucian — lepaskan beban masa lalu',
  Langkir:       'Tekad dan ambisi — gunakan dengan bijak agar tidak berlebihan',
  Medangsia:     'Ketenangan dan harmoni — biarkan hal mengalir secara alami',
  Pujut:         'Kontemplasi spiritual — hari untuk doa, puasa, atau meditasi',
  Pahang:        'Keberanian dan ketegasan — saatnya menghadapi tantangan',
  Krulut:        'Cinta dan ketertarikan — energi emosional yang kuat',
  Merakih:       'Semangat membara — kendalikan keinginan agar tidak melampaui batas',
  Tambir:        'Hambatan dan rintangan — kesabaran adalah senjata utama',
  Medangkungan:  'Perlindungan dan naungan — hari yang aman untuk langkah besar',
  Matal:         'Transformasi besar — bersiaplah untuk perubahan yang signifikan',
  Uye:           'Kelembutan dan kelenturan — ikuti arus, jangan melawan',
  Menail:        'Komitmen dan janji — hari baik untuk ikatan dan perjanjian',
  Prangbakat:    'Ikhlas melepaskan — pengorbanan membuka jalan yang lebih besar',
  Bala:          'Kekuatan dan ketahanan — hari penuh energi untuk tantangan besar',
  Ugu:           'Kecepatan dan kegesitan — manfaatkan momen yang bergerak cepat',
  Wayang:        'Antara nyata dan ilusi — cari kejernihan sebelum bertindak',
  Klawu:         'Pelepasan dan pembersihan — akhiri siklus dengan tuntas',
  Dukut:         'Perkumpulan dan pertemuan — energi sosial dan kolektif tinggi',
  Watugunung:    'Fondasi yang kuat — bangun dengan hati-hati agar abadi',
};

// ── Astrology ─────────────────────────────────────────────────────────────────

export const TRANSIT_ASPECT: Record<string, string> = {
  conjunction: 'energi menyatu — fokus dan intensitas penuh',
  opposition:  'tegangan dua kutub — integrasi adalah jawabannya',
  trine:       'harmoni mengalir — gunakan peluang ini dengan segera',
  square:      'gesekan produktif — pertumbuhan melalui tantangan',
  sextile:     'pintu terbuka kecil — usaha ringan membuka peluang',
};

export const PLANET_BRIEF: Record<string, string> = {
  Sun:          'jati diri dan vitalitas',
  Moon:         'emosi dan intuisi',
  Mercury:      'komunikasi dan pikiran',
  Venus:        'cinta, nilai, dan kesenangan',
  Mars:         'energi, ambisi, dan konflik',
  Jupiter:      'ekspansi, keberlimpahan, kebijaksanaan',
  Saturn:       'disiplin, batasan, tanggung jawab',
  Uranus:       'perubahan tiba-tiba, kebebasan, inovasi',
  Neptune:      'intuisi dalam, ilusi, spiritualitas',
  Pluto:        'transformasi mendalam, kekuatan, kelahiran kembali',
  'North Node': 'arah tujuan jiwa, pertumbuhan',
  'South Node': 'pola lama jiwa, kenyamanan masa lalu',
  Chiron:       'luka mendalam yang sedang disembuhkan',
  ASC:          'penampilan lahir dan cara menghadapi dunia',
  MC:           'karier dan reputasi publik',
};
